"""
E11 - SHAP Explainability

Purpose
-------
Explain treatment-success predictions generated by the E6
Random Forest classifier.

E11 does NOT train a new predictive model.

It loads:
    E6 - treatment_success_model.pkl

and generates SHAP feature contributions for individual
patient-treatment predictions.

Important interpretation
------------------------
SHAP values describe how features contribute to the model's
prediction.

They do NOT establish:
    - causality
    - treatment effectiveness
    - clinical risk
    - medical necessity
    - prescribing recommendations

The explanation is therefore a model-interpretability output.
"""


from pathlib import Path
import pickle
import joblib
import warnings

import numpy as np
import pandas as pd


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = BASE_DIR.parent.parent

E6_MODEL_PATH = (
    PROJECT_ROOT / "treatment_success_model.pkl"
)


# ============================================================
# CONFIGURATION
# ============================================================

TOP_FEATURES = 10


# ============================================================
# SHAP IMPORT
# ============================================================

try:

    import shap

except ImportError:

    raise ImportError(
        "SHAP is required for E11. "
        "Install it using: pip install shap"
    )


# ============================================================
# LOAD E6 MODEL
# ============================================================

def load_e6_model():

    if not E6_MODEL_PATH.exists():
        raise FileNotFoundError(
            f"E6 model artifact not found: {E6_MODEL_PATH}"
        )

    artifact = joblib.load(
        E6_MODEL_PATH
    )

    if not isinstance(artifact, dict):
        raise ValueError(
            "Invalid E6 model artifact."
        )

    if "model" not in artifact:
        raise ValueError(
            "E6 artifact missing 'model'."
        )

    if "feature_names" not in artifact:
        raise ValueError(
            "E6 artifact missing 'feature_names'."
        )

    return (
        artifact["model"],
        artifact["feature_names"]
    )


# ============================================================
# FEATURE CONSTRUCTION
# ============================================================

def build_prediction_features(
    patient_context,
    treatment_id,
    feature_names
):
    """
    Construct exactly the same feature representation used
    by E6 for inference.
    """

    row = {}

    # --------------------------------------------------------
    # Numerical features
    # --------------------------------------------------------

    row["age"] = patient_context.get(
        "age",
        0
    )

    vitals = patient_context.get(
        "vitals",
        {}
    )

    row["temperature"] = vitals.get(
        "temperature",
        0
    )

    row["heart_rate"] = vitals.get(
        "heart_rate",
        0
    )

    row["respiratory_rate"] = vitals.get(
        "respiratory_rate",
        0
    )

    row["systolic_bp"] = vitals.get(
        "systolic_bp",
        0
    )

    row["diastolic_bp"] = vitals.get(
        "diastolic_bp",
        0
    )

    row["spo2"] = vitals.get(
        "spo2",
        0
    )

    # --------------------------------------------------------
    # Categorical features
    # --------------------------------------------------------

    row["gender"] = str(
        patient_context.get(
            "gender",
            "UNKNOWN"
        )
    )

    row["disease_id"] = str(
        patient_context.get(
            "disease_id",
            "UNKNOWN"
        )
    )

    row["severity_id"] = str(
        patient_context.get(
            "severity_id",
            "UNKNOWN"
        )
    )

    row["treatment_id"] = str(
        treatment_id
    )

    # --------------------------------------------------------
    # Symptoms
    # --------------------------------------------------------

    symptom_vector = patient_context.get(
        "symptom_vector",
        {}
    )

    for symptom_name, value in symptom_vector.items():

        row[symptom_name] = value

    X = pd.DataFrame(
        [row]
    )

    # --------------------------------------------------------
    # Same encoding as E6
    # --------------------------------------------------------

    categorical_columns = [
        "gender",
        "disease_id",
        "severity_id",
        "treatment_id"
    ]

    X = pd.get_dummies(
        X,
        columns=[
            c
            for c in categorical_columns
            if c in X.columns
        ],
        dtype=float
    )

    # --------------------------------------------------------
    # Exact E6 feature alignment
    # --------------------------------------------------------

    X = X.reindex(
        columns=feature_names,
        fill_value=0
    )

    X = X.fillna(0)

    return X


# ============================================================
# SHAP EXPLAINER
# ============================================================

def create_explainer(model):
    """
    Create a TreeExplainer for the E6 Random Forest.
    """

    return shap.TreeExplainer(
        model
    )


# ============================================================
# EXTRACT POSITIVE-CLASS SHAP VALUES
# ============================================================

def get_positive_class_shap_values(
    explainer,
    X
):
    """
    Obtain SHAP values corresponding to the treatment-success
    / positive class.

    SHAP versions may return either:
        - list[class][sample][feature]
        - ndarray[sample][feature]
        - ndarray[sample][feature][class]

    This function normalizes those formats.
    """

    shap_values = explainer.shap_values(
        X
    )

    # --------------------------------------------------------
    # Older SHAP format:
    #
    # list:
    #     class 0 -> samples x features
    #     class 1 -> samples x features
    # --------------------------------------------------------

    if isinstance(
        shap_values,
        list
    ):

        if len(shap_values) < 2:

            raise ValueError(
                "Expected SHAP values for two classes."
            )

        return np.asarray(
            shap_values[1]
        )

    shap_values = np.asarray(
        shap_values
    )

    # --------------------------------------------------------
    # Newer SHAP format:
    #
    # samples x features x classes
    # --------------------------------------------------------

    if shap_values.ndim == 3:

        if shap_values.shape[2] >= 2:

            return shap_values[
                :,
                :,
                1
            ]

    # --------------------------------------------------------
    # Binary matrix:
    #
    # samples x features
    # --------------------------------------------------------

    if shap_values.ndim == 2:

        return shap_values

    raise ValueError(
        "Unsupported SHAP output shape: "
        f"{shap_values.shape}"
    )


# ============================================================
# EXPLAIN ONE TREATMENT
# ============================================================

def explain_treatment(
    patient_context,
    treatment_id,
    top_n=TOP_FEATURES
):
    """
    Generate SHAP explanation for one patient-treatment pair.
    """

    model, feature_names = load_e6_model()

    X = build_prediction_features(
        patient_context,
        treatment_id,
        feature_names
    )

    # --------------------------------------------------------
    # Model probability
    # --------------------------------------------------------

    model_probability = float(
        model.predict_proba(
            X
        )[0][1]
    )

    # --------------------------------------------------------
    # SHAP
    # --------------------------------------------------------

    explainer = create_explainer(
        model
    )

    shap_values = get_positive_class_shap_values(
        explainer,
        X
    )

    values = shap_values[0]

    # --------------------------------------------------------
    # Base value
    # --------------------------------------------------------

    expected_value = explainer.expected_value

    if isinstance(
        expected_value,
        (list, np.ndarray)
    ):

        expected_value = np.asarray(
            expected_value
        ).flatten()

        if len(expected_value) >= 2:

            base_value = float(
                expected_value[1]
            )

        else:

            base_value = float(
                expected_value[0]
            )

    else:

        base_value = float(
            expected_value
        )

    # --------------------------------------------------------
    # Feature contribution table
    # --------------------------------------------------------

    explanation_df = pd.DataFrame({
        "feature": feature_names,
        "feature_value": X.iloc[0].values,
        "shap_value": values
    })

    explanation_df[
        "absolute_shap_value"
    ] = explanation_df[
        "shap_value"
    ].abs()

    explanation_df = (
        explanation_df
        .sort_values(
            "absolute_shap_value",
            ascending=False
        )
        .reset_index(
            drop=True
        )
    )

    # --------------------------------------------------------
    # Top features
    # --------------------------------------------------------

    top_features = []

    for _, row in explanation_df.head(
        top_n
    ).iterrows():

        direction = (
            "INCREASES"
            if row["shap_value"] > 0
            else "DECREASES"
        )

        top_features.append({
            "feature": str(
                row["feature"]
            ),
            "feature_value": float(
                row["feature_value"]
            ),
            "shap_value": float(
                row["shap_value"]
            ),
            "absolute_shap_value": float(
                row["absolute_shap_value"]
            ),
            "direction": direction
        })

    return {
        "treatment_id": treatment_id,
        "model_type": (
            "Random Forest Classifier"
        ),
        "model_success_probability": (
            model_probability
        ),
        "base_value": base_value,
        "top_features": top_features,
        "explanation_method": (
            "SHAP TreeExplainer"
        ),
        "interpretation": (
            "SHAP values explain model feature "
            "contributions and do not establish causality "
            "or clinical treatment effectiveness."
        )
    }


# ============================================================
# EXPLAIN MULTIPLE TREATMENTS
# ============================================================

def explain_treatments(
    patient_context,
    treatment_ids,
    top_n=TOP_FEATURES
):
    """
    Generate SHAP explanations for multiple treatments.
    """

    results = []

    for treatment_id in treatment_ids:

        results.append(
            explain_treatment(
                patient_context,
                treatment_id,
                top_n=top_n
            )
        )

    return results


# ============================================================
# VALIDATE SHAP EXPLANATION
# ============================================================

def validate_explanation(
    explanation
):
    """
    Validate the E11 explanation structure.
    """

    required_fields = [
        "treatment_id",
        "model_type",
        "model_success_probability",
        "base_value",
        "top_features",
        "explanation_method",
        "interpretation"
    ]

    for field in required_fields:

        if field not in explanation:

            raise RuntimeError(
                "E11 explanation missing field: "
                f"{field}"
            )

    probability = explanation[
        "model_success_probability"
    ]

    if not np.isfinite(
        probability
    ):

        raise RuntimeError(
            "E11 produced a non-finite probability."
        )

    if not (
        0 <= probability <= 1
    ):

        raise RuntimeError(
            "E11 probability is outside [0, 1]."
        )

    if not isinstance(
        explanation["top_features"],
        list
    ):

        raise RuntimeError(
            "E11 top_features must be a list."
        )

    for feature in explanation[
        "top_features"
    ]:

        required_feature_fields = [
            "feature",
            "feature_value",
            "shap_value",
            "absolute_shap_value",
            "direction"
        ]

        for field in required_feature_fields:

            if field not in feature:

                raise RuntimeError(
                    "E11 feature explanation missing: "
                    f"{field}"
                )

        if feature[
            "direction"
        ] not in {
            "INCREASES",
            "DECREASES"
        }:

            raise RuntimeError(
                "Invalid SHAP direction."
            )


# ============================================================
# FIND TEST ENCOUNTER
# ============================================================

def find_valid_test_encounter(
    limit=500
):
    """
    Find an encounter that can pass through E1 and E2.
    """

    from ML.treatment_advisor.candidate_treatments import (
        generate_candidates_for_encounter
    )

    engine = get_database_engine()

    query = f"""
        SELECT
            encounter_id
        FROM patient_encounter
        WHERE recovery_days IS NOT NULL
        ORDER BY visit_timestamp
        LIMIT {int(limit)}
    """

    encounters = pd.read_sql(
        query,
        engine
    )

    if encounters.empty:

        raise RuntimeError(
            "No test encounters found."
        )

    last_error = None

    for encounter_id in encounters[
        "encounter_id"
    ].tolist():

        try:

            (
                context,
                candidates,
                candidate_records
            ) = generate_candidates_for_encounter(
                encounter_id
            )

            if (
                context is None
                or candidates is None
                or candidates.empty
            ):

                continue

            return (
                encounter_id,
                context,
                candidates
            )

        except Exception as e:

            last_error = e
            continue

    if last_error is not None:

        raise RuntimeError(
            "Could not find a valid E11 test encounter. "
            f"Last encountered error: {last_error}"
        )

    raise RuntimeError(
        "Could not find a valid E11 test encounter."
    )


# ============================================================
# DATABASE ENGINE
# ============================================================

def get_database_engine():
    """
    Import the project's existing database engine.
    """

    try:

        from database import get_engine

        return get_engine()

    except ImportError:

        raise ImportError(
            "Could not import project database engine."
        )


# ============================================================
# E11 PIPELINE TEST
# ============================================================

def run_e11_pipeline_test():
    """
    Test:

        E1 -> E2 -> E3 -> E4 -> E11

    E11 explains the E6 treatment-success model.
    """

    print()
    print("=" * 70)
    print("E11 PIPELINE TEST")
    print("=" * 70)

    from ML.treatment_advisor.clinical_eligibility import (
        load_treatment_master,
        evaluate_candidates
    )

    from ML.treatment_advisor.e4_configuration import (
        enrich_candidates
    )

    # ========================================================
    # FIND TEST ENCOUNTER
    # ========================================================

    (
        encounter_id,
        context,
        candidates
    ) = find_valid_test_encounter()

    print()
    print(
        f"Encounter ID : {encounter_id}"
    )

    print(
        f"Disease      : "
        f"{context.get('disease_id')}"
    )

    print(
        f"Severity     : "
        f"{context.get('severity_id')}"
    )

    # ========================================================
    # E1
    # ========================================================

    if not context:

        raise RuntimeError(
            "E1 patient context is empty."
        )

    print(
        "E1 context: VALID"
    )

    # ========================================================
    # E2
    # ========================================================

    if (
        candidates is None
        or candidates.empty
    ):

        raise RuntimeError(
            "E2 produced no candidates."
        )

    print(
        f"E2 candidates: "
        f"{len(candidates)}"
    )

    # ========================================================
    # E3
    # ========================================================

    treatment_master = (
        load_treatment_master()
    )

    eligible = evaluate_candidates(
        candidates,
        treatment_master
    )

    if (
        eligible is None
        or eligible.empty
    ):

        raise RuntimeError(
            "E3 produced no eligible candidates."
        )

    print(
        f"E3 candidates: "
        f"{len(eligible)}"
    )

    # ========================================================
    # HOSPITAL
    # ========================================================

    engine = get_database_engine()

    hospital_query = """
        SELECT
            hospital_id
        FROM patient_encounter
        WHERE encounter_id = %(encounter_id)s
    """

    hospital_df = pd.read_sql(
        hospital_query,
        engine,
        params={
            "encounter_id": encounter_id
        }
    )

    if hospital_df.empty:

        raise RuntimeError(
            "Hospital not found."
        )

    hospital_id = str(
        hospital_df.iloc[0][
            "hospital_id"
        ]
    )

    print(
        f"Hospital     : "
        f"{hospital_id}"
    )

    # ========================================================
    # E4
    # ========================================================

    enriched = enrich_candidates(
        eligible,
        hospital_id
    )

    if (
        enriched is None
        or enriched.empty
    ):

        raise RuntimeError(
            "E4 produced no candidates."
        )

    print(
        f"E4 candidates: "
        f"{len(enriched)}"
    )

    # ========================================================
    # E11
    # ========================================================

    treatment_ids = (
        enriched[
            "treatment_id"
        ]
        .dropna()
        .astype(str)
        .tolist()
    )

    if not treatment_ids:

        raise RuntimeError(
            "No treatment IDs available for E11."
        )

    print()
    print("-" * 70)
    print("E11 SHAP EXPLANATIONS")
    print("-" * 70)

    explanations = explain_treatments(
        context,
        treatment_ids,
        top_n=TOP_FEATURES
    )

    # ========================================================
    # DISPLAY
    # ========================================================

    for explanation in explanations:

        print()
        print(
            f"Treatment ID: "
            f"{explanation['treatment_id']}"
        )

        print(
            f"E6 model probability: "
            f"{explanation['model_success_probability']:.4f}"
        )

        print(
            f"SHAP base value: "
            f"{explanation['base_value']:.4f}"
        )

        print(
            "Top contributing features:"
        )

        for feature in explanation[
            "top_features"
        ]:

            print(
                f"  {feature['feature']}: "
                f"{feature['shap_value']:+.6f} "
                f"({feature['direction']})"
            )

    # ========================================================
    # VALIDATION
    # ========================================================

    if len(explanations) == 0:

        raise RuntimeError(
            "E11 produced no explanations."
        )

    for explanation in explanations:

        validate_explanation(
            explanation
        )

    print()
    print("=" * 70)
    print("E11 VALIDATION: PASSED")
    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print("=" * 70)
    print("E11 - SHAP EXPLAINABILITY")
    print("=" * 70)

    run_e11_pipeline_test()


if __name__ == "__main__":
    main()